### ISSUE TITLE
MQMQA pair outputs for API

### ISSUE THREAD

**Issue by parikshitbajpai** [ORNL-CEES/thermochimica#141]
**Reason.**
Quads are the "species" in MQMQA and as such their values are returned when looking for mole fractions for example. However, users might be more interested in the pairs which are more obvious as species for multiphysics applications. Let the users request pairs are outputs

**Proposed Solution**
Not much on Thermochimica side. Just add a function to check if a phase is MQMQA phase, a function to return the possible pairs in addition to quads. The other functions are already in `MQMQAFunctions.f90`.

**Impact**
User facing interface improves.

**Additional context**
Will be required by a MOOSE Thermochimica Integration PR.

**Comment by maxposchmann** [comment]
Is this not what you want:
https://github.com/ORNL-CEES/thermochimica/blob/c9d054deed746b7c646b2dc289c4548294e7a19f/src/api/CouplingUtilitiesISO_C.f90#L861

**Comment by parikshitbajpai** [comment]
It is and I used it for the mole fractions but we also want to check if a phase specified in a MOOSE input file is an MQM phase or not and check whether the corresponding species in the input are present in the simulation or not. Like we do in https://github.com/parikshitbajpai/moose/blob/733d515c7bb40436172c7516c2f52c3883f7cf2d/modules/chemical_reactions/src/userobjects/ThermochimicaNodalData.C#LL110C7-L120C6
