### ISSUE TITLE
New data for YH

### ISSUE THREAD

**Issue by tophmatthews** [ORNL-CEES/thermochimica#147]
**Reason.**
I've been testing out Thermochimica integration with MOOSE (via @dschwen 's helpful pointers) for metal hydrides in NEAMS. I've been testing out the Zr-H model capabilities, which are extensive. Is it possible to add Y-H into the data already available? I believe the necessary information is in [FactPS](https://www.crct.polymtl.ca/fact/documentation/FSData.htm.). 

**Proposed Solution**
Add Y-H into current databases in `/data`.

**Impact**
This will enable coupling with MOOSE tools for metal hydride modeling.

**Additional context**
The MOOSE integration makes the strong case for including Thermochimica information for a host of simulations, as long as data is available. Happy to help implementation as well, thanks!

**Comment by parikshitbajpai** [comment]
@markuspiro and @dschwen can better judge but imo adding the Y-H datafile in `data/` might lead to copyright issues. I think we can generate the datafile and use it without adding to the repo. Would that work for you @tophmatthews? I'll also try to find a open-source database for the system.

**Comment by tophmatthews** [comment]
Ah perhaps there are problems there with copyright issues. What would be an alternative? Can you point me towards the appropriate licensing contacts to license the relevant databases? Do you all use the FactSage databases? Thanks!

**Comment by parikshitbajpai** [comment]
You should get call / email from Markus soon. The way we have done this usually is to use databases that are publicly available or generate a `*.dat` format datafile from FactSage and use it locally without checking it into the repo. Markus knows the licensing aspect better so he can let you know what the best way might be.

**Comment by tophmatthews** [comment]
Awesome, Thanks!

**Comment by parikshitbajpai** [comment]
Having talked with @markuspiro, I believe he is working on getting this data file to @tophmatthews. I'll close this issue for now since we won't be adding the file to the repo.
