### ISSUE TITLE
Thermochimica GUI reporting incorrect results for NiF2-KF system

### ISSUE THREAD

**Issue by parikshitbajpai** [ORNL-CEES/thermochimica#57]
## Bug Description
As seen in the following image, Thermochimica GUI is reporting an _incorrect result_ for non-solvable systems instead of graceful exit with error message.

![image](https://user-images.githubusercontent.com/45185043/135382789-0b80acd8-e98d-4492-964e-b4c6d8bed32a.png)

## Information to Reproduce
- OS: Mac
- Branch: guiBeta
- Commit: https://github.com/ORNL-CEES/thermochimica/commit/b5e19b87c021fafc61c0caeb0dedcc1f313f510d
- Script: `python/thermoGui.py`

## Impact
This creates confusion and gives a false sense of code working. Can be highly misleading to users who might not be well versed with computational thermochemistry and they might doubt the capability of the code.

**Comment by maxposchmann** [comment]
This was an issue with the new retry feature, fixed in b1beb5a15af5a1f56bc140920bf307dd967eeb1f
