### ISSUE TITLE
Disable input editing while result window is open

### ISSUE THREAD

**Issue by parikshitbajpai** [ORNL-CEES/thermochimica#58]
## Reason
Currently, while the result window is open, the GUI allows the user to edit the input data and click on the run button even though it results in no action. This can be confusing to users who might think that something is wrong or the program is not working. Even worse, if the user does not carefully review the results and the system information within it, they might end up working with the wrong data.  

## Possible solutions
We should considering disabling the input boxes while the result window is open. Alternatively, the edit can be allowed as they are right now but hitting the `Run` button should then terminate the current output and rerun the calculations.

## Impact
Better user experience. Remove possible source of confusion.

**Comment by maxposchmann** [comment]
Fixed in 46e116535c13b4920552f3cb71718ee68e686e96
Results window is not closed, but new results window is created. This allows for side-by-side comparison.
