### ISSUE TITLE
Parsing a SUBG data block

### ISSUE THREAD

**Issue by rtaylo45** [ORNL-CEES/thermochimica#8]
There is an issue with parsing a dat file in the mstdb data base. I am seeing this error.
```
At line 98 of file src/ParseCSDataBlockSUBG.f90
Fortran runtime error: Index '12' of dimension 1 of array 'cdummyvec' outside of expected range (3:1)
```
If you look at the line in file `ParseCSDATABlockSUBG.f90` there is a comment right above this line saying 
```
    ! Read in names of constituents on first sublattice:
    ! NOTE: THIS LINE MAY NEED TO BE REVISED IF THERE ARE A LARGE # OF CONSTITUENTS:
    read (1,*,IOSTAT = INFO) cDummyVec(1:iTempVec(1)) 
```

Markus im not sure if you know about this data base but it looks like Ted is a member. The data base is held on an internal ORNL git server.

**Comment by maxposchmann** [comment]
@rtaylo45 Does simply changing the dimension of cDummyVec to 12 (or higher) in its declaration solve this issue?

**Comment by rtaylo45** [comment]
I did that then I got this issue
```At line 105 of file src/ParseCSDataBlockSUBG.f90
Fortran runtime error: Index '12' of dimension 1 of array 'dtempvec' outside of expected range (6:1)
```
Then i changed the dimension of dtempvec to 12. When i ran again i got this error 
```
Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7F17544F0BF7
#1  0x7F17544EFDF0
#2  0x7F17539E627F
#3  0x7F17539E6207
#4  0x7F17539E78F7
#5  0x7F1753A28D26
#6  0x7F1753A31488
#7  0xB75B0F in resetthermoparser_ at ResetThermoParser.f90:74 (discriminator 26)
#8  0xB74668 in resetthermoall_ at ResetThermoAll.f90:36
#9  0x40DDA8 in __test_transportedspecies_MOD_thermotypemstdb at Test_TransportedSpecies.F90:2910 (discriminator 2)
#10  0x40DE3A in __test_transportedspecies_MOD_test_transportedspecies_driver at Test_TransportedSpecies.F90:50
#11  0x40BC95 in masstransport_unit_test_driver at massTransport_unit_test_driver.f90:13
#12  0x7F17539D23D4
Aborted (core dumped)
```
I havn't tried anything else past this

**Comment by maxposchmann** [comment]
That's too bad, an easy fix would have been nice.

I guess we have run into that "large # of constituents" condition. It will be hard to debug without having the input file, is there a way you can share it?

**Comment by rtaylo45** [comment]
Im not sure. Let me look into that

**Comment by rtaylo45** [comment]
You are Markus should have received an email about getting access to the repo

**Comment by maxposchmann** [comment]
I bumped the dimensions of those arrays up to 20 and don't see the SIGABRT that you got. However, I also don't get a successful calculation. Using the debugger I found that there are a number of SUBM phases in the dat file, and SUBM isn't a supported format. Is SUBM equivalent to one of the supported formats (IDMX, QKTO, SUBL, RKMP, RKMPM, SUBLM, SUBG), or do we need to implement a new phase?

**Comment by rtaylo45** [comment]
Shit… I was afraid of that. Let me look into some stuff

**Comment by maxposchmann** [comment]
It's a good idea to call ThermoDebug before ResetThermo (I think that's where your code crashed). If you do that with this case, you get the message "DEBUG: The data-file contains a solution phase type that is not currently supported by Thermochimica." followed by a list of the available solution models.

**Comment by markuspiro** [comment]
Zack,

Sorry about the delay. Looking through the e-mails, it seems that the issue is that you have some data-file that is using the SUBM model. I have never dealt with this type of model. A cursory look tells me that this is another model type used for molten salts; however, I have no idea how that differs from SUBG or SUBQ. I would advise against using that data-file – at least for now. In fact, it would be helpful if you could send me that file.

FYI, Parikshit is currently working on modifying Thermochimica for SUBQ. You may want to ping him.

You may be aware that Max and I are in Knoxville. Hope to see you at the lab tomorrow. Let us know if you want to go for dinner/beer tomorrow night.

Cheers,
Markus
